[package]
name = "audioPlayer"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
eframe = "0.31.0"
mp3-duration = "0.1.10"
percentage = "0.1.0"
rodio = "0.20.1"
symphonia = "0.5.4"
tokio = { version = "1.43.0", features = ["full"] }
